/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('primevue/badge')['default']
    Button: typeof import('primevue/button')['default']
    DataView: typeof import('primevue/dataview')['default']
    Dock: typeof import('./../components/Dock.vue')['default']
    Drawer: typeof import('primevue/drawer')['default']
    Popover: typeof import('primevue/popover')['default']
    PortfolioDetailDrawer: typeof import('./../components/PortfolioDetailDrawer.vue')['default']
    ScreenshotDrawer: typeof import('./../components/ScreenshotDrawer.vue')['default']
    SectionGitHub: typeof import('./../components/SectionGitHub.vue')['default']
    SectionPortfolio: typeof import('./../components/SectionPortfolio.vue')['default']
    SectionProfile: typeof import('./../components/SectionProfile.vue')['default']
    SectionTimeline: typeof import('./../components/SectionTimeline.vue')['default']
    Select: typeof import('primevue/select')['default']
    SelectButton: typeof import('primevue/selectbutton')['default']
    Skeleton: typeof import('primevue/skeleton')['default']
    SpotlightCard: typeof import('./../components/SpotlightCard.vue')['default']
    SquaresBackground: typeof import('./../components/SquaresBackground.vue')['default']
    TargetCursor: typeof import('./../components/TargetCursor.vue')['default']
  }
}
